version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: dante
      POSTGRES_PASSWORD: dante123456
      POSTGRES_DB: library
  backend:
    build:
      context: ./django/
    ports:
      - 8080:8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py loaddata fixtures/proj.json fixtures/admin.json
      && gunicorn config.wsgi -b 0.0.0.0:8080 "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx