# Generated by Django 4.1.7 on 2023-04-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='todomodel',
            options={'ordering': ['created']},
        ),
    ]
